# Generated by Django 4.1.2 on 2024-04-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braian_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='file_uploads/'),
        ),
    ]
